"""
TPC-H Q14: Promotion Effect Query

Business question:
    Determines what percentage of revenue in a given year and month was
    generated by promotional items.

SQL semantics:
    SELECT 100.00 * sum(CASE WHEN p_type LIKE 'PROMO%'
                             THEN l_extendedprice*(1-l_discount)
                             ELSE 0 END)
                  / sum(l_extendedprice*(1-l_discount)) AS promo_revenue
    FROM lineitem, part
    WHERE l_partkey = p_partkey
      AND l_shipdate >= DATE '1995-09-01'
      AND l_shipdate < DATE '1995-10-01';

UDF mapping:
    - WHERE date filter → UDF returns None to discard
    - CASE WHEN promo check → UDF returns (promo_value, total_value)
    - SUM / ratio → handled by Flink SQL
"""


def udf_q14(shipdate, p_type, extendedprice, discount):
    """
    Pure-Python UDF for TPC-H Q14.

    Parameters
    ----------
    shipdate : str
        l_shipdate in 'YYYY-MM-DD' format.
    p_type : str
        p_type.
    extendedprice : float
        l_extendedprice.
    discount : float
        l_discount.

    Returns
    -------
    tuple or None
        (promo_value, total_value) if row passes date filter; None otherwise.
        promo_value is disc_price if p_type starts with 'PROMO', else 0.
    """
    if shipdate < '1995-09-01' or shipdate >= '1995-10-01':
        return None

    disc_price = float(extendedprice * (1 - discount))
    promo = disc_price if p_type.startswith('PROMO') else 0.0
    return (promo, disc_price)


# --------------- Runner metadata ---------------

UDF_INPUTS = [
    'l_shipdate', 'p_type',
    'l_extendedprice', 'l_discount',
]

UDF_RESULT_TYPE = 'ROW<`promo` FLOAT, `total` FLOAT>'

SQL = (
    "SELECT "
    "  100.00 * SUM(r.promo) / SUM(r.total) AS promo_revenue "
    "FROM ("
    "  SELECT udf_q14(l_shipdate, p_type, l_extendedprice, l_discount) "
    "    AS (promo, total) "
    "  FROM lineitem "
    "  JOIN part ON l_partkey = p_partkey"
    ") r "
    "WHERE r.promo IS NOT NULL"
)
