#!/usr/bin/env bash
# Run PyTorch Inductor demo twice with two torch-source instrumentation sets.
# This script executes inside the pytorch-runner container.

set -euo pipefail

WORKLOAD_DIR="${WORKLOAD_DIR:-/opt/pytorch-workload}"
RESULT_DIR="${RESULT_DIR:-/opt/pytorch-results}"
FIXED_PERF_DIR="${FIXED_PERF_DIR:-/home/w30063991}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
DEMO_SCRIPT="${DEMO_SCRIPT:-$WORKLOAD_DIR/test/inductor_train.py}"
BACKUP_ROOT="${BACKUP_ROOT:-/tmp/pytorch-source-backup}"
COMBINED_TIMING_TXT="$RESULT_DIR/pytorch-compile-times.txt"

export OMP_WAIT_POLICY=PASSIVE
export GOMP_SPINCOUNT=0
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export DYNAMO_PERF_COLLECT=1
export PYTORCH_DEMO_DIM="${PYTORCH_DEMO_DIM:-256}"
export PYTORCH_DEMO_DEPTH="${PYTORCH_DEMO_DEPTH:-100}"

mkdir -p "$FIXED_PERF_DIR" "$RESULT_DIR" "$BACKUP_ROOT"
chmod 777 "$FIXED_PERF_DIR" "$RESULT_DIR" || true
: > "$COMBINED_TIMING_TXT"

TORCH_DIR="$($PYTHON_BIN - <<'PY'
import pathlib, torch
print(pathlib.Path(torch.__file__).parent)
PY
)"

echo "[run-inductor] TORCH_DIR=$TORCH_DIR"
echo "[run-inductor] WORKLOAD_DIR=$WORKLOAD_DIR"
echo "[run-inductor] RESULT_DIR=$RESULT_DIR"
echo "[run-inductor] DEMO_SCRIPT=$DEMO_SCRIPT"
echo "[run-inductor] COMBINED_TIMING_TXT=$COMBINED_TIMING_TXT"

backup_file() {
    local target="$1"
    local rel="${target#/}"
    local backup="$BACKUP_ROOT/$rel"
    mkdir -p "$(dirname "$backup")"
    if [ -e "$target" ]; then
        cp -a "$target" "$backup"
        echo "file" > "$backup.__kind"
    else
        echo "missing" > "$backup.__kind"
    fi
}

restore_file() {
    local target="$1"
    local rel="${target#/}"
    local backup="$BACKUP_ROOT/$rel"
    local kind_file="$backup.__kind"
    if [ ! -f "$kind_file" ]; then
        echo "[run-inductor] WARNING: no backup metadata for $target" >&2
        return
    fi
    if [ "$(cat "$kind_file")" = "file" ]; then
        cp -a "$backup" "$target"
    else
        rm -f "$target"
    fi
}

append_compile_txt() {
    local case_name="$1"
    local case_dir="$RESULT_DIR/$case_name"
    local case_timing_txt="$case_dir/compile-times.txt"
    : > "$case_timing_txt"

    # Ignore bytecode_tracing_*_metadata.txt. Only compile txt generated by
    # the demo script is timing evidence for this pipeline.
    local found=0
    while IFS= read -r -d '' txt; do
        found=1
        {
            echo "===== CASE: $case_name FILE: $(basename "$txt") ====="
            cat "$txt"
            echo
        } >> "$case_timing_txt"
    done < <(find "$case_dir" -maxdepth 1 -type f -name '*.txt' ! -name '*_metadata.txt' ! -name 'compile-times.txt' -print0 | sort -z)

    {
        echo "===== CASE: $case_name ====="
        if [ "$found" -eq 1 ]; then
            cat "$case_timing_txt"
        else
            echo "[run-inductor] WARNING: no compile txt found for $case_name"
        fi
        echo
    } >> "$COMBINED_TIMING_TXT"
}

archive_outputs() {
    local case_name="$1"
    local case_dir="$RESULT_DIR/$case_name"
    mkdir -p "$case_dir"
    # Keep local perf.data outputs. Metadata txt from bytecode tracing is not
    # timing evidence and is intentionally ignored.
    find "$FIXED_PERF_DIR" -maxdepth 1 -type f -name '*.data' -exec mv -f {} "$case_dir" \; 2>/dev/null || true
    while IFS= read -r -d '' data_file; do
        local base
        local sanitized
        base="$(basename "$data_file")"
        sanitized="${base//:/-}"
        if [ "$base" != "$sanitized" ]; then
            mv -f "$data_file" "$case_dir/$sanitized"
        fi
    done < <(find "$case_dir" -maxdepth 1 -type f -name '*.data' -print0)
    find "$FIXED_PERF_DIR" -maxdepth 1 -type f -name '*_metadata.txt' -delete 2>/dev/null || true
    # The demo writes <arch>_compile.txt in WORKLOAD_DIR because it runs with
    # cwd=$WORKLOAD_DIR. Move that per-run compile text next to the data files.
    find "$WORKLOAD_DIR" -maxdepth 1 -type f -name '*_compile.txt' -exec mv -f {} "$case_dir" \; 2>/dev/null || true
    append_compile_txt "$case_name"
}

clear_fixed_outputs() {
    find "$FIXED_PERF_DIR" -maxdepth 1 -type f \( -name '*.data' -o -name '*.txt' \) -delete 2>/dev/null || true
    find "$WORKLOAD_DIR" -maxdepth 1 -type f -name '*_compile.txt' -delete 2>/dev/null || true
}

run_case() {
    local case_name="$1"
    local modified_dir="$WORKLOAD_DIR/get_perf_data/$case_name/modified_file"
    local case_dir="$RESULT_DIR/$case_name"
    local -a restore_targets=()
    local status=0
    mkdir -p "$case_dir"
    clear_fixed_outputs

    echo "[run-inductor] Running case: $case_name"
    if [ "$case_name" = "aot_trace" ]; then
        local compile_fx="$TORCH_DIR/_inductor/compile_fx.py"
        local graph_compile="$TORCH_DIR/_functorch/_aot_autograd/graph_compile.py"
        local inductor_perf="$TORCH_DIR/_inductor/wkf_your_perf_module.py"
        local aot_perf="$TORCH_DIR/_functorch/_aot_autograd/wkf_your_perf_module.py"
        restore_targets=("$compile_fx" "$graph_compile" "$inductor_perf" "$aot_perf")
        for target in "${restore_targets[@]}"; do backup_file "$target"; done
        cp -a "$modified_dir/compile_fx.py" "$compile_fx" || status=$?
        cp -a "$modified_dir/graph_compile.py" "$graph_compile" || status=$?
        cp -a "$modified_dir/wkf_your_perf_module.py" "$inductor_perf" || status=$?
        cp -a "$modified_dir/wkf_your_perf_module.py" "$aot_perf" || status=$?
    elif [ "$case_name" = "bytecode_tracing" ]; then
        local output_graph="$TORCH_DIR/_dynamo/output_graph.py"
        local perf_collector="$TORCH_DIR/_dynamo/perf_collector_data.py"
        restore_targets=("$output_graph" "$perf_collector")
        for target in "${restore_targets[@]}"; do backup_file "$target"; done
        cp -a "$modified_dir/output_graph.py" "$output_graph" || status=$?
        cp -a "$modified_dir/perf_collector_data.py" "$perf_collector" || status=$?
    else
        echo "Unknown case: $case_name" >&2
        return 2
    fi

    if [ "$status" -eq 0 ]; then
        set +e
        (cd "$WORKLOAD_DIR" && "$PYTHON_BIN" "$DEMO_SCRIPT") >"$case_dir/stdout.log" 2>"$case_dir/stderr.log"
        status=$?
        set -e
    fi

    archive_outputs "$case_name"
    for target in "${restore_targets[@]}"; do restore_file "$target"; done

    if [ "$status" -ne 0 ]; then
        echo "[run-inductor] Case $case_name failed with exit $status" >&2
        return "$status"
    fi
    echo "[run-inductor] Case $case_name completed"
}

run_case aot_trace
run_case bytecode_tracing
chmod 666 "$COMBINED_TIMING_TXT" || true

echo "[run-inductor] All cases completed. Results under $RESULT_DIR"
